version: "3"
services:
 
    oj_redis:
        image: oj_redis:1.0
        container_name: oj_redis
        restart: always
        volumes:
          - $PWD/data/redis:/data

    oj_nginx:
        image: oj_nginx:1.0
        container_name: oj_nginx
        depends_on:
          - oj_core
        ports:
          - 80:80
        links:
          - oj_core:oj_core
        volumes:
          - $PWD/data/nginx/html:/usr/share/nginx/html
          - $PWD/data/nginx/log:/var/log/nginx
          - $PWD/data/nginx/nginx.conf:/etc/nginx/nginx.conf
          - $PWD/data/nginx/conf.d:/etc/nginx/conf.d
        restart: always
        
    oj_rabbitmq: 
        image: oj_rabbitmq:1.0
        container_name: oj_rabbitmq
        restart: always
        
    oj_mysql:
        image: oj_mysql:1.0
        container_name: oj_mysql
        restart: always
        volumes:
          - $PWD/data/mysql:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=398653206 #密码请不要更改
    
    oj_core:
        image: oj_core:1.0
        container_name: oj_core
        restart: always
        cap_drop:
         - SYS_CHROOT
         - MKNOD
        environment: 
          - JUDGE_PATH=/home/onlinejudge
        depends_on:
          - oj_mysql
          - oj_rabbitmq
          - oj_redis
        links:
          - oj_mysql:oj_mysql
          - oj_rabbitmq:OJ_rabbitmq
          - oj_redis:oj_redis
        volumes:
          - $PWD/data/core:/home/onlinejudge
