spring:
  datasource:
    hikari:
      username: root
      password: 398653206
      driver-class-name: com.mysql.jdbc.Driver
      max-lifetime: 176500
      connection-timeout: 30000
      minimum-idle: 1
    url: jdbc:mysql://localhost:3306/onlinejudge?useUnicode=true&characterEncoding=utf8&useSSL=false
  redis:
    host: 172.17.0.3
    port: 6379
    password: 398653206
    timeout: 500    #超时时间
    pool:
      maxWaitMillis: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
  servlet:
    multipart:
      max-file-size: 50MB

rabbitmq:
  host: 172.17.0.4
  username: siney
  password: 398653206
  port: 5672
  size: 2

server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    accesslog:
      enabled: true
      pattern: common
  servlet:
    session:
      timeout: 1800
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jsut.ecoder.po
logging:
  level:
    root: info
    com:
      jsut:
        ecoder:
          dao: DEBUG
  file: /home/siney/桌面/log/a.log

